apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-build-task
spec:
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/projectquay/golang:1.24
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/bash
        set -e

        echo "🔧 Installing CA certificates and dev tools..."
        dnf install -y \
          ca-certificates \
          curl \
          tar \
          gcc \
          gcc-c++ \
          git \
          make \
          diffutils \
          which \
          cmake \
          openssl \
          nss-tools

        # Fix: Ensure trust store structure exists
        mkdir -p /etc/pki/ca-trust/extracted/pem
        mkdir -p /etc/pki/ca-trust/source/anchors
        update-ca-trust force-enable
        update-ca-trust extract
        dnf clean all

        export HOME=/tekton/home
        export SSL_CERT_DIR=/etc/pki/ca-trust/extracted/pem
        export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt

        echo "🔧 Installing Rust via rustup..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

        if [ -f "$HOME/.cargo/env" ]; then
          source "$HOME/.cargo/env"
        else
          echo "⚠️ Warning: $HOME/.cargo/env not found, falling back..."
          export PATH="$HOME/.cargo/bin:$PATH"
        fi

        rustup default stable
        rustc --version
        cargo --version

        echo "🔧 Installing Ginkgo..."
        go install github.com/onsi/ginkgo/ginkgo@latest
        export PATH=$PATH:$(go env GOPATH)/bin
        ginkgo version

        echo "🧪 Running Ginkgo tests..."
        cd $(workspaces.source.path)
        go env -w GOFLAGS=-buildvcs=false
        make build
